name = "Dracula"
family = "dracula"
source = "https://github.com/dracula"
description = "A dark theme for many editors, shells, and more."

[[programs]]
name = "alacritty"
file = "alacritty.toml"

[[programs]]
name = "kitty"
file = "kitty.conf"
