# Catppuccin for kitty
foreground ${color.text}
background ${color.base}
color0     ${color.surface1}
color1     ${color.red}
color2     ${color.green}
color3     ${color.yellow}
color4     ${color.blue}
color5     ${color.pink}
color6     ${color.teal}
color7     ${color.subtext1}
