# Adwaita for kitty
foreground ${color.text}
background ${color.base}
color0     ${color.black}
color1     ${color.red}
color2     ${color.green}
color3     ${color.yellow}
color4     ${color.blue}
color5     ${color.magenta}
color6     ${color.cyan}
color7     ${color.white}
