# Rosé Pine for kitty
foreground ${color.text}
background ${color.base}
color0     ${color.overlay}
color1     ${color.love}
color2     ${color.pine}
color3     ${color.gold}
color4     ${color.foam}
color5     ${color.iris}
color6     ${color.rose}
color7     ${color.text}
