# Dracula for kitty
foreground ${color.text}
background ${color.base}
color0     ${color.currentline}
color1     ${color.red}
color2     ${color.green}
color3     ${color.yellow}
color4     ${color.purple}
color5     ${color.pink}
color6     ${color.cyan}
color7     ${color.text}
