# Poimandres for Alacritty
[colors.primary]
background = "${color.base}"
foreground = "${color.text}"

[colors.normal]
black   = "${color.black}"
red     = "${color.red}"
green   = "${color.green}"
yellow  = "${color.yellow}"
blue    = "${color.blue}"
magenta = "${color.magenta}"
cyan    = "${color.cyan}"
white   = "${color.white}"
